#!/bin/bash

master_branch='master'
development_branch='development' 
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

echo "Running pre-commit checks"

#cd into jmt_src and attempt to build
cd jmt_src
ant spatial_queue_commit_tests
if [ $? != 0 ]; then
  echo "Tests failed, not committing"
  exit 1
else
  echo "Tests passed"
fi

cd ..

if [ $development_branch = $current_branch ] 
then  
    echo "You're trying to commit directly to development."
    exec < /dev/tty

    while true; do
      read -p "Is this really what you want to do? (Y/n) " yn
      if [ "$yn" = "" ]; then
        yn='Y'
      fi
      case $yn in
          [Yy] ) exit 0;;
          [Nn] ) exit 1;;
          * ) echo "Please answer y or n for yes or no.";;
      esac
    done
fi
if [ $master_branch = $current_branch ] 
then  
    echo "You're trying to commit directly to master."
    echo "Stop."
    exit 1
fi